import { Country, Region, eSIMPackage } from "@/types";

const generatePackages = (countryName: string, countryId: string): eSIMPackage[] => [
  { id: `${countryId}-5gb`, name: `${countryName} eSIM 5GB`, data: "5GB", duration: "7 Days", price: "$15", countryName },
  { id: `${countryId}-10gb`, name: `${countryName} eSIM 10GB`, data: "10GB", duration: "15 Days", price: "$25", countryName },
  { id: `${countryId}-20gb`, name: `${countryName} eSIM 20GB`, data: "20GB", duration: "30 Days", price: "$40", countryName },
  { id: `${countryId}-unl`, name: `${countryName} eSIM Unlimited`, data: "Unlimited", duration: "15 Days", price: "$55", countryName },
];

const IMAGES = {
  Turkey: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_12e40ee0-b787-4540-8879-3e109f849c4d.jpg",
  France: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_e81501cd-751f-479f-9471-4ac9381016a5.jpg",
  Thailand: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_12172330-b1ef-4c32-9bac-9ea5b2f62e40.jpg",
  Malaysia: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_4dd05024-c2af-4f9a-a268-fd6f331f2f67.jpg",
  Japan: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_3138b9af-83d8-4da4-9191-6d88642499dc.jpg",
  "United Kingdom": "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_10e850a4-2f00-4f8f-a5b6-3c5576d35040.jpg",
  USA: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_40a7564a-9422-4250-bdba-7b2634e017c4.jpg",
  Italy: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_8cf5031b-5752-4e7b-9838-88c7672ee133.jpg",
  Spain: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_c2db73c7-cb20-42dc-89f0-ad107e521379.jpg",
  Germany: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_76a0326b-6210-4e8c-9829-655a56fcc363.jpg",
  Switzerland: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_b4d192aa-d17f-4c73-8738-1a71257e6d19.jpg",
  Australia: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_13226e74-12eb-4c5b-9de5-037f9e2fc171.jpg",
  UAE: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_cc79877d-f97c-41da-a5f0-b676fdee0a8d.jpg",
  Egypt: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_6a546bed-d76e-4e66-8f7f-baaf5aae1d92.jpg",
  Brazil: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_ffbce4e6-7725-4e7f-bec5-cb30fae11a2e.jpg",
  Greece: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_b0a354d6-0758-4d83-ab86-6b2277e28ebb.jpg",
  "South Korea": "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_57d6a312-e417-43cb-ac96-265bde54bc1a.jpg",
  Singapore: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_b1d4a918-78db-47bc-b12f-799e8c952f3f.jpg",
  Indonesia: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_f52669ca-d99f-4ea9-b1cc-27f2bcc9b461.jpg",
  Vietnam: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_b4566a3b-6865-4d86-80b4-3e0dbcf8ae06.jpg",
  India: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_f98c7a3f-a56b-438c-af1a-0d5584968eff.jpg",
  Mexico: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_cb28e420-4219-4659-a122-496df05031c8.jpg",
  Canada: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_accc965b-90bc-492e-b5b4-aaa614537ffc.jpg",
  "South Africa": "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_f0e11a0c-ec37-46ad-883c-51ea2921a89b.jpg",
};

const GENERIC_IMAGES = Object.values(IMAGES);

const getCountryImage = (name: string, index: number) => {
  // @ts-ignore
  if (IMAGES[name]) return IMAGES[name];
  // Deterministic random image based on index
  return GENERIC_IMAGES[index % GENERIC_IMAGES.length];
};

const COUNTRY_LIST = [
  // Featured
  { code: "tr", name: "Turkey" },
  { code: "fr", name: "France" },
  { code: "th", name: "Thailand" },
  { code: "my", name: "Malaysia" },
  { code: "jp", name: "Japan" },
  { code: "gb", name: "United Kingdom" },
  { code: "us", name: "USA" },
  { code: "it", name: "Italy" },
  { code: "es", name: "Spain" },
  { code: "de", name: "Germany" },
  { code: "ch", name: "Switzerland" },
  { code: "au", name: "Australia" },
  { code: "ae", name: "UAE" },
  { code: "eg", name: "Egypt" },
  { code: "br", name: "Brazil" },
  { code: "gr", name: "Greece" },
  { code: "kr", name: "South Korea" },
  { code: "sg", name: "Singapore" },
  { code: "id", name: "Indonesia" },
  { code: "vn", name: "Vietnam" },
  { code: "in", name: "India" },
  { code: "mx", name: "Mexico" },
  { code: "ca", name: "Canada" },
  { code: "za", name: "South Africa" },
  // A-Z (Partial list for 195+ representation)
  { code: "af", name: "Afghanistan" },
  { code: "al", name: "Albania" },
  { code: "dz", name: "Algeria" },
  { code: "ad", name: "Andorra" },
  { code: "ao", name: "Angola" },
  { code: "ag", name: "Antigua and Barbuda" },
  { code: "ar", name: "Argentina" },
  { code: "am", name: "Armenia" },
  { code: "at", name: "Austria" },
  { code: "az", name: "Azerbaijan" },
  { code: "bs", name: "Bahamas" },
  { code: "bh", name: "Bahrain" },
  { code: "bd", name: "Bangladesh" },
  { code: "bb", name: "Barbados" },
  { code: "by", name: "Belarus" },
  { code: "be", name: "Belgium" },
  { code: "bz", name: "Belize" },
  { code: "bj", name: "Benin" },
  { code: "bt", name: "Bhutan" },
  { code: "bo", name: "Bolivia" },
  { code: "ba", name: "Bosnia and Herzegovina" },
  { code: "bw", name: "Botswana" },
  { code: "bn", name: "Brunei" },
  { code: "bg", name: "Bulgaria" },
  { code: "bf", name: "Burkina Faso" },
  { code: "bi", name: "Burundi" },
  { code: "kh", name: "Cambodia" },
  { code: "cm", name: "Cameroon" },
  { code: "cv", name: "Cape Verde" },
  { code: "cf", name: "Central African Republic" },
  { code: "td", name: "Chad" },
  { code: "cl", name: "Chile" },
  { code: "cn", name: "China" },
  { code: "co", name: "Colombia" },
  { code: "km", name: "Comoros" },
  { code: "cg", name: "Congo" },
  { code: "cr", name: "Costa Rica" },
  { code: "hr", name: "Croatia" },
  { code: "cu", name: "Cuba" },
  { code: "cy", name: "Cyprus" },
  { code: "cz", name: "Czech Republic" },
  { code: "dk", name: "Denmark" },
  { code: "dj", name: "Djibouti" },
  { code: "dm", name: "Dominica" },
  { code: "do", name: "Dominican Republic" },
  { code: "ec", name: "Ecuador" },
  { code: "sv", name: "El Salvador" },
  { code: "gq", name: "Equatorial Guinea" },
  { code: "er", name: "Eritrea" },
  { code: "ee", name: "Estonia" },
  { code: "et", name: "Ethiopia" },
  { code: "fj", name: "Fiji" },
  { code: "fi", name: "Finland" },
  { code: "ga", name: "Gabon" },
  { code: "gm", name: "Gambia" },
  { code: "ge", name: "Georgia" },
  { code: "gh", name: "Ghana" },
  { code: "gd", name: "Grenada" },
  { code: "gt", name: "Guatemala" },
  { code: "gn", name: "Guinea" },
  { code: "gw", name: "Guinea-Bissau" },
  { code: "gy", name: "Guyana" },
  { code: "ht", name: "Haiti" },
  { code: "hn", name: "Honduras" },
  { code: "hk", name: "Hong Kong" },
  { code: "hu", name: "Hungary" },
  { code: "is", name: "Iceland" },
  { code: "ir", name: "Iran" },
  { code: "iq", name: "Iraq" },
  { code: "ie", name: "Ireland" },
  { code: "il", name: "Israel" },
  { code: "jm", name: "Jamaica" },
  { code: "jo", name: "Jordan" },
  { code: "kz", name: "Kazakhstan" },
  { code: "ke", name: "Kenya" },
  { code: "ki", name: "Kiribati" },
  { code: "kw", name: "Kuwait" },
  { code: "kg", name: "Kyrgyzstan" },
  { code: "la", name: "Laos" },
  { code: "lv", name: "Latvia" },
  { code: "lb", name: "Lebanon" },
  { code: "ls", name: "Lesotho" },
  { code: "lr", name: "Liberia" },
  { code: "ly", name: "Libya" },
  { code: "li", name: "Liechtenstein" },
  { code: "lt", name: "Lithuania" },
  { code: "lu", name: "Luxembourg" },
  { code: "mo", name: "Macau" },
  { code: "mk", name: "North Macedonia" },
  { code: "mg", name: "Madagascar" },
  { code: "mw", name: "Malawi" },
  { code: "mv", name: "Maldives" },
  { code: "ml", name: "Mali" },
  { code: "mt", name: "Malta" },
  { code: "mh", name: "Marshall Islands" },
  { code: "mr", name: "Mauritania" },
  { code: "mu", name: "Mauritius" },
  { code: "fm", name: "Micronesia" },
  { code: "md", name: "Moldova" },
  { code: "mc", name: "Monaco" },
  { code: "mn", name: "Mongolia" },
  { code: "me", name: "Montenegro" },
  { code: "ma", name: "Morocco" },
  { code: "mz", name: "Mozambique" },
  { code: "mm", name: "Myanmar" },
  { code: "na", name: "Namibia" },
  { code: "nr", name: "Nauru" },
  { code: "np", name: "Nepal" },
  { code: "nl", name: "Netherlands" },
  { code: "nz", name: "New Zealand" },
  { code: "ni", name: "Nicaragua" },
  { code: "ne", name: "Niger" },
  { code: "ng", name: "Nigeria" },
  { code: "no", name: "Norway" },
  { code: "om", name: "Oman" },
  { code: "pk", name: "Pakistan" },
  { code: "pw", name: "Palau" },
  { code: "pa", name: "Panama" },
  { code: "pg", name: "Papua New Guinea" },
  { code: "py", name: "Paraguay" },
  { code: "pe", name: "Peru" },
  { code: "ph", name: "Philippines" },
  { code: "pl", name: "Poland" },
  { code: "pt", name: "Portugal" },
  { code: "qa", name: "Qatar" },
  { code: "ro", name: "Romania" },
  { code: "ru", name: "Russia" },
  { code: "rw", name: "Rwanda" },
  { code: "kn", name: "Saint Kitts and Nevis" },
  { code: "lc", name: "Saint Lucia" },
  { code: "vc", name: "Saint Vincent and the Grenadines" },
  { code: "ws", name: "Samoa" },
  { code: "sm", name: "San Marino" },
  { code: "st", name: "Sao Tome and Principe" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "sn", name: "Senegal" },
  { code: "rs", name: "Serbia" },
  { code: "sc", name: "Seychelles" },
  { code: "sl", name: "Sierra Leone" },
  { code: "sk", name: "Slovakia" },
  { code: "si", name: "Slovenia" },
  { code: "sb", name: "Solomon Islands" },
  { code: "so", name: "Somalia" },
  { code: "lk", name: "Sri Lanka" },
  { code: "sd", name: "Sudan" },
  { code: "sr", name: "Suriname" },
  { code: "se", name: "Sweden" },
  { code: "sy", name: "Syria" },
  { code: "tw", name: "Taiwan" },
  { code: "tj", name: "Tajikistan" },
  { code: "tz", name: "Tanzania" },
  { code: "tl", name: "Timor-Leste" },
  { code: "tg", name: "Togo" },
  { code: "to", name: "Tonga" },
  { code: "tt", name: "Trinidad and Tobago" },
  { code: "tn", name: "Tunisia" },
  { code: "tm", name: "Turkmenistan" },
  { code: "tv", name: "Tuvalu" },
  { code: "ug", name: "Uganda" },
  { code: "ua", name: "Ukraine" },
  { code: "uy", name: "Uruguay" },
  { code: "uz", name: "Uzbekistan" },
  { code: "vu", name: "Vanuatu" },
  { code: "va", name: "Vatican City" },
  { code: "ve", name: "Venezuela" },
  { code: "ye", name: "Yemen" },
  { code: "zm", name: "Zambia" },
  { code: "zw", name: "Zimbabwe" },
];

export const COUNTRIES: Country[] = COUNTRY_LIST.map((c, index) => ({
  id: c.name.toLowerCase().replace(/ /g, "-"),
  name: c.name,
  flagUrl: `https://flagcdn.com/${c.code}.svg`,
  imageUrl: getCountryImage(c.name, index),
  packages: generatePackages(c.name, c.name.toLowerCase().replace(/ /g, "-")),
}));

export const REGIONS: Region[] = [
  {
    id: "europe",
    name: "Europe",
    packages: [
      { id: "eu-10gb", name: "Europe eSIM 10GB", data: "10GB", duration: "30 Days", price: "$35", category: "Europe" },
      { id: "eu-20gb", name: "Europe eSIM 20GB", data: "20GB", duration: "30 Days", price: "$60", category: "Europe" },
    ],
  },
  {
    id: "asia",
    name: "Asia",
    packages: [
      { id: "as-10gb", name: "Asia eSIM 10GB", data: "10GB", duration: "30 Days", price: "$30", category: "Asia" },
      { id: "as-20gb", name: "Asia eSIM 20GB", data: "20GB", duration: "30 Days", price: "$55", category: "Asia" },
    ],
  },
  {
    id: "middle-east",
    name: "Middle East",
    packages: [
      { id: "me-10gb", name: "Middle East eSIM 10GB", data: "10GB", duration: "30 Days", price: "$45", category: "Middle East" },
    ],
  },
];

export const GLOBAL_PLANS: eSIMPackage[] = [
  { id: "global-10gb", name: "Global eSIM 10GB", data: "10GB", duration: "30 Days", price: "$65", category: "Global" },
  { id: "global-20gb", name: "Global eSIM 20GB", data: "20GB", duration: "60 Days", price: "$110", category: "Global" },
  { id: "global-unlimited", name: "Global Unlimited", data: "Unlimited", duration: "30 Days", price: "$150", category: "Global" },
];
